spring:
  data:
    redis:
      host: localhost
      port: 6379
      password:  some-password
  ai:
    ollama:
      embedding:
        model: "llama2"
        options:
          temperature: 0.5
          top-p: 0.2
          top-k: 2
          num-g-p-u: 1 #enable metal gpu on MAC
      base-url: "http://localhost:11434"
      chat:
        model: "llama2"
